[phases.setup]
nixPkgs = ['php82', 'php82Packages.composer', 'nodejs_20', 'npm-9_x']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist',
    'npm install'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:clear',
    'php artisan cache:clear',
    'php artisan view:clear',
    'php artisan route:clear'
]

[start]
cmd = 'php artisan config:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8000}'
